variable "vpc_id" {}
variable "subnet_ids" {}
variable "private_subnet_ids" {}
variable "lambda_invoke_arn" {}
variable "lambda_function_name" {}
variable "prefix" {}
variable "load_balancer_arn" {}
variable "auth_lambda_invoke_arn" {}
variable "auth_lambda_function_name" {}